{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "reflector.fullname" . }}
  labels:
    app: {{ include "reflector.name" . }}
    app.kubernetes.io/name: {{ include "reflector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "reflector"
    {{- include "labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs:
    - "get"
    - "watch"
    - "update"
    - "list"
    - "create"
{{- if .Values.cascadeDelete }}
    - "delete"
{{- end }}
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "reflector.fullname" . }}
  labels:
    app: {{ include "reflector.name" . }}
    app.kubernetes.io/name: {{ include "reflector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "reflector"
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "reflector.fullname" . }}
subjects:
  - name: {{ template "reflector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end }}
