apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "reflector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "reflector.name" . }}
    app.kubernetes.io/name: {{ template "reflector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: "reflector"
    {{- include "labels" . | nindent 4 }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "reflector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: "reflector"
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "reflector.name" . }}
        app.kubernetes.io/name: {{ template "reflector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: "reflector"
        {{- include "labels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
      {{- if and .Values.metrics.enabled (not .Values.metrics.servicemonitor.enabled) }}
      {{- if not .Values.podAnnotations }}
      annotations:
      {{- end }}
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      {{- end }}
    spec:
      serviceAccountName: {{ template "reflector.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.image }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}{{- if (.digest) -}}@{{.digest}}{{- else -}}:{{ default $.Chart.AppVersion .tag }}{{- end -}}"
          # If it is 40 then it is definitely the image line
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /reflector
        {{- if .Values.verbose }}
          - --verbose
        {{- end }}
        {{- if (not .Values.metrics.enabled) }}
          - --metrics=false
        {{- end }}
        {{- if .Values.concurrency }}
        {{- if .Values.concurrency.reflect }}
          - --reflect-concurrency={{ .Values.concurrency.reflect }}
        {{- end }}
        {{- if .Values.concurrency.worker }}
          - --worker-concurrency={{ .Values.concurrency.worker }}
        {{- end }}
        {{- end }}
        {{- if (and .Values.metrics.host .Values.metrics.port) }}
          - --metrics-addr={{ printf "%s:%d" .Values.metrics.host .Values.metrics.port }}
        {{- else }}
          - --metrics-addr=0.0.0.0:8080
        {{- end }}
        {{- if .Values.cascadeDelete }}
          - --cascade-delete
        {{- end }}
        {{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 10 }}
        {{- end }}
          ports:
          - containerPort: 8080
            protocol: TCP
            name: metrics
          livenessProbe:
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            httpGet:
              path: healthz
              port: metrics
          readinessProbe:
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            httpGet:
              path: ready
              port: metrics
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
