{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "reflector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "reflector.name" . }}
    app.kubernetes.io/name: {{ include "reflector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "reflector"
    {{- include "labels" . | nindent 4 }}
{{- if .Values.serviceLabels }}
{{ toYaml .Values.serviceLabels | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: metrics
      targetPort: {{ .Values.metrics.servicemonitor.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "reflector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "reflector"
{{- end }}
