// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RateLimiter is an autogenerated mock type for the RateLimiter type
type RateLimiter struct {
	mock.Mock
}

// AddRateLimited provides a mock function with given fields: _a0
func (_m *RateLimiter) AddRateLimited(_a0 interface{}) {
	_m.Called(_a0)
}
