name: Coverage
on: 
  push:
    branches:
    - root

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          go:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'
          - 'test/e2e/**/*'

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs:
    - filter
    if: |
      (needs.filter.outputs.go == 'true')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go 1.21.5
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.21.5

    - name: Generate coverage report
      run: |
        make coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v2.0.3
      with:
        file: ./test/coverage.out
        flags: unittests
        name: codecov-umbrella
