name: codecov
on: 
  push:
    branches:
    - root

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.17

    - name: Generate coverage report
      run: |
        make coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v2.0.3
      with:
        file: ./test/coverage.out
        flags: unittests
        name: codecov-umbrella
