name: Docs
on: 
  push:
    branches:
    - root

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Build
      run: |
        pip install mkdocs mkdocs_material

    - name: Deploy
      run: |
        make docs/release
