name: Docs
on: 
  push:
    branches:
    - root

jobs:
  changes:
    name: Filter Changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          docs:
          - 'docs/**/*'
          - '.config/mkdocs.yaml'
          # trigger when we edit the job
          - '.github/workflow/docs.yaml'

  deploy:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.docs == 'true')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Build
      run: |
        pip install mkdocs mkdocs_material
        make docs/release

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs
        publish_dir: ./site
        cname: reflector.havulv.io
