name: Docs
on: 
  push:
    branches:
    - root

jobs:
  changes:
    name: Filter Changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          docs:
          - 'docs/**/*'
          - '.config/mkdocs.yaml'

  deploy:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.docs == 'true')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Build
      run: |
        pip install mkdocs mkdocs_material

    - name: Deploy
      run: |
        make docs/release
